server:
  port: 8081

spring:
  application:
    # 应用名称
    name: service-consumer
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/micro_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: root
    password: password

# 配置Eureka Server注册中心
eureka:
  instance:
    # 主机名, 不配置的时候将根据操作系统的主机名称来获取
    hostname: localhost
    # 是否开启IP地址注册
    prefer-ip-address: true
    # 主机地址+端口号
    #instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      # 注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/
    # 是否将自己注册到注册中心,默认为true
    register-with-eureka: true
    # 表示Eureka Client 间隔多长时间服务器来取注册信息,默认为30秒
    registry-fetch-interval-seconds: 10

# 负载均衡策略
# service-provider 是指被调用者的微服务名称
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadBalancer.RandomRule